### ISSUE TITLE
Debian 9 os detection fails

### ISSUE THREAD

**Issue by ScorpioT1000** [vaimo/binary-chromedriver#1]
Debian 9 returns "Linux" instead of "linux" in PHP_OS so it makes sense to use strtolower in os detector

**Comment by allanpaiste** [comment]
Shouldn't this be fine due to the only place where PHP_OS is directly in use is at ...

https://github.com/vaimo/webdriver-binary-downloader/blob/master/src/Analysers/PlatformAnalyser.php#L10

... where case-insensitivity is in action?

**Comment by ScorpioT1000** [comment]
Indeed, this might be a lbaey/chromedriver issue that was cached before
